# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1cec6d25d7d7abc31cfda17ff59248676bd94789d5f5398889c48fd99918ebb9b5f5dc3bc1241a9ff64b1943c30fcae5835575ab929b8f84b27bbb5710dc8e4

test:
  secret_key_base: 584fdc0b754d83330c25bb0fddfdf131950bbd8751474606c42e914c27be4c64e4952b3d89713ab76173b10185c04e8a2cb118de2deb5ec050cb766c10269dd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
